# Numpy array in pyhton
# what is numpy
### 1. its an external package used to work ARRAYS AND MATRIX
### 2. ARRAY AND MATRIX are different aspects in Numpy
### 3. Array is not a matrix
### 4. while work with numpy in python, we need to decide whether to take in arrays or matrix..


## 1. what is array
### Its a collection of similar items/elements
### In general, for production environment, anaconda will not be used , there seperate environment , there python will be installed as organisation version, then pip install numpy then import....
### that is for security purpose we will do all the above.

In [5]:
# Install numpy
!pip install numpy

In [6]:
# import numpy
import numpy as np

In [8]:
# To creat 1-D array (it looks like a list)
list = [1,2,3,4,5,6]
oneDimArrayExample = np.array(list)
oneDimArrayExample

array([1, 2, 3, 4, 5, 6])

In [12]:
oneDimArrayExample.shape

(6,)

In [13]:
type(oneDimArrayExample)

numpy.ndarray

####-- without Numpy, Python also allows us to creat an array but it is memory exhaust\  
####-- if you want use RAM effectively when you are working with BIG DATA especially \
####--- Better use NUMPY Array rather than Python array, reason is memory Optimization, otherwise no iisues with python array to use.

In [15]:
# define number of dimensions in np.array
oneDimArrayExample.ndim

1

In [16]:
# two dimensional array..it looks exactly like matrix but not so.
twoDimArray = np.array([
    [],
    [],
    [],
])
# this example of 3*3 dimensional array

In [17]:
twoDimArray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
twoDimArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
twoDimArray.ndim

2

In [20]:
twoDimArray.shape

(3, 3)

In [21]:
type(twoDimArray)

numpy.ndarray

#### Big difference between Array and matrix in numpy
#### In Arrays, elementwise operation, always it takes same element of different arrays (1*1, 2*2....should be used np.array()
#### But in Matrix, its not the case, it will multiple rows to columns...should be used np.matrix()
####
#### you need not use loops to perform multiplication in python, automatically it will give us to do the same with formula

In [24]:
# Multiplication two array 
# In arrays, element wise operation
twoDimArray * twoDimArray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
# In Matrix # rows and columns operations
twoDimMatrix = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [26]:
twoDimMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
twoDimMatrix.shape

(3, 3)

In [28]:
twoDimMatrix.ndim

2

In [29]:
type(twoDimMatrix)

numpy.matrix

In [30]:
twoDimMatrix * twoDimMatrix

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [31]:
twoDimArray * twoDimArray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
# In Data Science world , Majorily Arrays will be used.
# Matrix basically used in Image classification/segmentation and image processing in DL

In [33]:
# All arthimetic operations canbe done in numpy

In [34]:
twoDimArray **3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [35]:
twoDimArray / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [38]:
twoDimMatrix **3

matrix([[ 468,  576,  684],
        [1062, 1305, 1548],
        [1656, 2034, 2412]])