In [1]:
# changing dimensions in arrays

In [2]:
# import numpy
import numpy as np

In [3]:
data = np.random.randint(0,100,9) # total 9 values will be printed

In [4]:
data

array([64, 50, 23, 37, 15, 46, 73, 77, 43])

In [5]:
# dimensios?
data.ndim

1

In [11]:
# how to change dimensions
data1=data.reshape(3,3)

In [12]:
data1.ndim

2

In [13]:
data.reshape(2,2)

ValueError: cannot reshape array of size 9 into shape (2,2)

In [14]:
data.reshape(1,9)

array([[64, 50, 23, 37, 15, 46, 73, 77, 43]])

In [15]:
data.reshape(9,1)

array([[64],
       [50],
       [23],
       [37],
       [15],
       [46],
       [73],
       [77],
       [43]])

In [16]:
# to convert 1d---2d we used reshape function

In [17]:
# to convert 2d--1d we use ravel()

In [19]:
data1.ravel()

array([64, 50, 23, 37, 15, 46, 73, 77, 43])