In [1]:
# import numpy
import numpy as np

In [2]:
data1 = np.random.randint(0,100,9)

In [3]:
data1

array([47, 72, 22, 29, 10, 25, 33, 68, 21])

In [4]:
#Extracting 4th element in the list 
data1[3]

29

In [5]:
data1[3:7]

array([29, 10, 25, 33])

In [6]:
data2 = data1.reshape(3,3)

In [7]:
data2

array([[47, 72, 22],
       [29, 10, 25],
       [33, 68, 21]])

In [8]:
data2[1:2] # 2nd row and 3 columns

array([[29, 10, 25]])

In [9]:
data2[2,2]

21

In [10]:
data2[2][2]

21

In [11]:
data2[2,:1]

array([33])

In [12]:
# syntax for extracting elements 
# data[starting row: ending row, starting column: ending column]
data2[0:2,0:2]

array([[47, 72],
       [29, 10]])

In [13]:
data2[1:3,1:3]

array([[10, 25],
       [68, 21]])

In [14]:
data2[1:,1:]

array([[10, 25],
       [68, 21]])

In [15]:
# Fancy indexing to extract different elements in the array
data2

array([[47, 72, 22],
       [29, 10, 25],
       [33, 68, 21]])

In [16]:
# extract [96 32]
#         [87 10]
#Fancy indexing helps to extract
#     rows indexing.  column indexing
# 96      0.             0.
# 32      0.             2.
# 87      2.             0.
# 10      2.             2.

In [17]:
# syntex
# arrayname[ [Row index], [column index]]
data2[[0,0,2,2], [0,2,0,2]]

array([47, 22, 33, 21])

In [18]:
type(data2)

numpy.ndarray

In [19]:
data2.shape

(3, 3)

In [20]:
data2.ndim

2

In [21]:
# but for 2*2 shape array
data2[[0,0,2,2],[0,2,0,2]].reshape(2,2)

array([[47, 22],
       [33, 21]])

In [22]:
dataExercise = np.arange(0,100,25).reshape(5,5)

ValueError: cannot reshape array of size 4 into shape (5,5)

In [23]:
dataExcercise =np.arange(0,100,25)

In [24]:
dataExercise

NameError: name 'dataExercise' is not defined

In [25]:
dataExcercise = np.arange(0,100)

In [26]:
dataExcercise

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
dataExcercise1 = np.arange(0,100,10)

In [28]:
dataExcercise1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
data2Ex = np.arange(0,100,25)

In [30]:
data2Ex

array([ 0, 25, 50, 75])

In [31]:
data2Ex.reshape(2,2)

array([[ 0, 25],
       [50, 75]])

In [32]:
data2Exercise = np.arange(0,100,4).reshape(5,5)

In [33]:
data2Exercise

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [36]:
# Extract24,28,32
# extract 64,68,72
data2Exercise[[1,1,1,3,3,3],[1,2,3,1,2,3]].reshape(2,3)

array([[24, 28, 32],
       [64, 68, 72]])

In [38]:
# range method to extract the elements 
data2Exercise[1:3,1:5]

array([[24, 28, 32, 36],
       [44, 48, 52, 56]])