In [1]:
# import numpy
import numpy as np

In [2]:
data = np.random.randint(0,100,9)

In [3]:
data

array([76, 99, 76, 57, 95,  6, 97, 26, 61])

In [4]:
data==6

array([False, False, False, False, False,  True, False, False, False])

In [6]:
data[data==6]

array([6])

In [7]:
data>=25

array([ True,  True,  True,  True,  True, False,  True,  True,  True])

In [8]:
data[data>=25]

array([76, 99, 76, 57, 95, 97, 26, 61])

In [9]:
# Logical Operator
data[data>=20 & data<=50]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
# error thrown because logical operator conditions should be in tuple()

In [11]:
data[(data>=20) & (data<=50)]

array([26])

In [12]:
data[(data>=20) & (data<=80)]

array([76, 76, 57, 26, 61])