In [1]:
#import numpy
import numpy as np

In [4]:
data = np.arange(1,100,5)

In [5]:
data

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [6]:
np.sqrt(data)

array([1.        , 2.44948974, 3.31662479, 4.        , 4.58257569,
       5.09901951, 5.56776436, 6.        , 6.40312424, 6.78232998,
       7.14142843, 7.48331477, 7.81024968, 8.1240384 , 8.42614977,
       8.71779789, 9.        , 9.2736185 , 9.53939201, 9.79795897])

In [8]:
np.sin(data)

array([ 0.84147098, -0.2794155 , -0.99999021, -0.28790332,  0.83665564,
        0.76255845, -0.40403765, -0.99177885, -0.15862267,  0.90178835,
        0.67022918, -0.521551  , -0.96611777, -0.02655115,  0.95105465,
        0.56610764, -0.62988799, -0.92345845,  0.10598751,  0.98358775])

In [10]:
np.sin(90)

0.8939966636005579

In [11]:
# it si in radians

In [13]:
np.sin(Pi/2)

NameError: name 'Pi' is not defined

In [14]:
np.exp(0)

1.0

In [15]:
np.exp(data)

array([2.71828183e+00, 4.03428793e+02, 5.98741417e+04, 8.88611052e+06,
       1.31881573e+09, 1.95729609e+11, 2.90488497e+13, 4.31123155e+15,
       6.39843494e+17, 9.49611942e+19, 1.40934908e+22, 2.09165950e+24,
       3.10429794e+26, 4.60718663e+28, 6.83767123e+30, 1.01480039e+33,
       1.50609731e+35, 2.23524660e+37, 3.31740010e+39, 4.92345829e+41])

In [16]:
np.log(10)

2.302585092994046

In [17]:
np.log(1)

0.0

In [18]:
np.log(data)

array([0.        , 1.79175947, 2.39789527, 2.77258872, 3.04452244,
       3.25809654, 3.4339872 , 3.58351894, 3.71357207, 3.8286414 ,
       3.93182563, 4.02535169, 4.11087386, 4.18965474, 4.26267988,
       4.33073334, 4.39444915, 4.4543473 , 4.51085951, 4.56434819])